### PR TITLE
#88: Add some files to configure the project for release 4.0.0

### PR DESCRIPTION
**Pull request by benedeki**
Same changes as in #89 only for the `release/4.0.0`

### CODE REVIEW

**Review by dk1844 — DISMISSED** [review]
LGTM (just read the code). 

Sure, but why don't we just merge master to `release/4.0.0`?

**Comment by benedeki** [comment]
> 
> 
> LGTM (just read the code).
> 
> Sure, but why don't we just merge master to `release/4.0.0`?

I asked, Sasa preferred a PR, you didn't say your opinion. 😉

**Comment by Zejnilovic** [comment]
> > LGTM (just read the code).
> > Sure, but why don't we just merge master to `release/4.0.0`?
> 
> I asked, Sasa preferred a PR, you didn't say your opinion. 😉

My bad. I meant a PR to merge it from master to release/4.0.0, not a stand-alone branch.

**Comment by benedeki** [comment]
> 
> 
> > > LGTM (just read the code).
> > > Sure, but why don't we just merge master to `release/4.0.0`?
> > 
> > 
> > I asked, Sasa preferred a PR, you didn't say your opinion. 😉
> 
> My bad. I meant a PR to merge it from master to release/4.0.0, not a stand-alone branch.

Ah,I see, sorry. Misunderstanding is half of the fun in Internet 😉

**Review by Zejnilovic — APPROVED** [review]

**Review by dk1844 — APPROVED** [review]

**Pull request merged**
